### ISSUE TITLE
Gaussian Log Reader for Optimization Scans

### ISSUE THREAD

**Issue by rmhuch** [McCoyGroup/McUtils#2]
Hello, 

I am working with a number of Gaussian scans some where optimization is allowed at every step and some where the coordinates are kept rigid. I've noticed the `log` formatting is different between the two types and that there are some properties that have parsers for the two different types, for example`"Dipole Moments"` and `"OptimizedDipoleMoments"`. 

I believe that the Mulliken Charges (like the dipole moments) are calculated at every step of the optimization scan, which means when I parse them using `"MullikenCharges"` I end up with a random number some times up to five times larger than my scan size. So I am interested in learning more about how the `"OptimizedDipoleMoment"` parser handles this data as when I use that I only get back a number of dipole moments equivalent to my scan size and I would like to be able to implement this type of handling to the Mulliken Charges as well as other properties.

Thanks for the help!

**Comment by b3m2a1** [comment]
See the (newly) extended docs here: https://mccoygroup.github.io/McUtils/McUtils/GaussianInterface.html
